import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
  const { data, status } = useSession();
  const router = useRouter();

  const handleSearch = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const input = e.currentTarget[0] as HTMLInputElement;
    const value = input.value;

    if (value) {
      void router.push(`/${value}`);
    }
  };

  return (
    <>
      <Head>
        <title>資料庫專題</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-tr from-primary to-secondary">
        <div className="container flex flex-col items-center justify-center gap-12">
          <h1 className="text-4xl font-bold text-white sm:text-[5rem]">
            {status === "authenticated" ? (
              <p>
                哈囉, <span>{data.user.name}</span>
              </p>
            ) : (
              <p>哈囉, 想去哪裡呢</p>
            )}
          </h1>

          <div className="flex w-full max-w-md flex-col items-center gap-4">
            <form className="form-control w-full" onSubmit={handleSearch}>
              <div className="input-group">
                <input
                  type="text"
                  placeholder="輸入學號來前往"
                  className="input-bordered input w-full"
                />
                <button className="btn-square btn">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6 fill-none stroke-current"
                    viewBox="0 0 24 24"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                  >
                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg>
                </button>
              </div>
            </form>
            {status === "authenticated" ? (
              <div className="grid w-full grid-cols-2 gap-2">
                <Link className="btn" href={`/${data.user.id}`}>
                  前往我的網頁
                </Link>
                <button className="btn" onClick={() => void signOut()}>
                  登出
                </button>
              </div>
            ) : (
              <button
                className="btn w-full"
                onClick={() => void signIn("fcu-nid")}
              >
                登入
              </button>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
