import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { signIn, signOut } from "next-auth/react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: sessionData, status } = useSession();
  const router = useRouter();

  const { data } = api.user.getAll.useQuery();

  const handleSearch = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    const input = e.currentTarget[0] as HTMLInputElement;
    const value = input.value;

    if (value) {
      void router.push(`/${value}`);
    }
  };

  return (
    <>
      <Head>
        <title>資料庫專題</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center bg-gradient-to-tr from-primary to-secondary">
        <div className="container flex flex-col items-center justify-center gap-12">
          <h1 className="text-4xl font-bold text-white sm:text-[5rem]">
            {status === "authenticated" ? (
              <p>
                嗨, <span>{sessionData.user.name}</span>
              </p>
            ) : (
              <p>哈囉, 想去哪裡呢</p>
            )}
          </h1>

          <div className="flex w-full max-w-md flex-col items-center gap-4">
            <form className="form-control w-full" onSubmit={handleSearch}>
              <div className="input-group">
                <input
                  type="text"
                  placeholder="輸入學號來前往"
                  className="input-bordered input w-full"
                />
                <button className="btn-square btn">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6 fill-none stroke-current"
                    viewBox="0 0 24 24"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                  >
                    <path d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg>
                </button>
              </div>
            </form>
            {status === "authenticated" ? (
              <div className="grid w-full grid-cols-2 gap-2">
                <Link className="btn" href={`/${sessionData.user.id}`}>
                  前往我的網頁
                </Link>
                <button className="btn" onClick={() => void signOut()}>
                  登出
                </button>
              </div>
            ) : (
              <button
                className="btn w-full"
                onClick={() => void signIn("fcu-nid")}
              >
                登入
              </button>
            )}
          </div>
        </div>
        <p className="text-md absolute bottom-5 animate-bounce text-white">
          往下滑動以瀏覽所有使用者
        </p>
      </main>
      <main className="flex h-screen flex-col items-center justify-center bg-gradient-to-br from-[#e0c3fc] to-[#8ec5fc]">
        <div className="container flex flex-wrap items-center justify-center gap-12">
          {data?.map((user, index) => (
            <Link
              href={`/${user.id}`}
              className="card w-72 bg-base-100 shadow-xl transition-all duration-300 ease-in-out hover:scale-105 hover:shadow-2xl"
              key={index}
            >
              <picture>
                <img
                  alt="Avatar"
                  src={user.image || "/images/avatar.png"}
                  className="h-72 rounded-t-xl object-cover"
                />
              </picture>
              <div className="card-body items-center text-center">
                <h2 className="card-title">{user.name}</h2>
                <p>{user.position}</p>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
